### ISSUE TITLE
Unable to use all nodes/threads setup for Databricks Compute 

### ISSUE THREAD

**Issue by songhan89** [dask-contrib/dask-databricks#36]
Hi,

Thansk for creating this library. 

I am trying to spin up Dask cluster on Azure Databricks.  

1. I've followed the instructions and managed to setup a dask cluster. However, i realised that the compute resources are not maximized. There is only 1 worker instead of 2 (based on the minimum number of workers I configured). Any idea how to fix this ? I have tried to use `client.cluster.scale(n=2)` but got an error returned.

2. Second issue is that i realised that URL for the dask dashboard is not accessible and is different if you are using Azure Databricks. The typical URL of an Azure databricks notebook is as followed:

https://adb-1486644750497365.5.azuredatabricks.net/?o=1486644750497365#notebook/1676261431997434/command/1676261431997440

<img width="969" alt="config" src="https://github.com/dask-contrib/dask-databricks/assets/15259500/3adc16f9-5026-4f01-b4b5-16a93f358d11">
<img width="1219" alt="client_cluster" src="https://github.com/dask-contrib/dask-databricks/assets/15259500/44f77e8a-a1fb-4e7a-97ab-69171f33ef9a">

Thanks and any advice is much appreciated.

**Comment by jacobtomlinson** [comment]
1. I would expect two Dask workers to be created. You can't use the scaling functionality in Dask because we are leveraging Databricks to start the processes. Can you take a look at the logs from the init scripts to see why the second worker is failing to start?
2. Yep we should definitely be handling this URL differently. I don't know enough about how Azure Databricks handles proxying to know what the new URL should be, but I'm sure we can find out. We also need a way to detect if the user is on Azure Databricks, maybe there is an environment variable that would tell us?

_Further, you've raised an issue with two separate questions. Could I ask you to open a second issue and split them out so we can handle them separately?_

**Comment by songhan89** [comment]
Hi @jacobtomlinson ,

Thanks for the advice. Turned out there was some Azure quota issue and wasn't really because of any issue with the library. I tried it on a different workspace without quota limitation and the issue went away. Apologies as I should have checked this in advance.

Closing this issue. Will create a separate issue for the azure databricks URL.
